[package]
name = "rua"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7"
anyhow = "1"
thiserror = "1"
once_cell = "1.19"
tracing = "0.1"

[dev-dependencies]
indoc = "2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
